#!/bin/bash

# Auto-generated by Folunar Workbench
# Facts: kernel, cpu_model

echo '=== Kernel Info ==='
echo 'Kernel: 7.0.11-arch1-1'
uname -a

echo '=== cpu_model ==='
['INFO']

echo '=== Summary ==='
echo 'kernel=7.0.11-arch1-1'
echo 'cpu_model=Intel(R) Core(TM) Ultra 9 185H'
