#!/bin/bash

# Auto-generated by Folunar Workbench
# Facts: node_name, cpu_model, users, kernel_release

echo '=== node_name ==='
['cat', '/proc/version']

echo '=== cpu_model ==='
['INFO']

echo '=== users ==='
['SEARCH']

echo '=== kernel_release ==='
['cat', '/proc/version']

echo '=== Summary ==='
echo 'node_name=d5b0433845ec'
echo 'cpu_model=Intel(R) Core(TM) Ultra 9 185H'
echo 'users=_apt,backup,bin,daemon,games,irc,list,lp'
echo 'kernel_release=#1'
