#!/bin/bash

# Auto-generated by Folunar Workbench
# Facts: disk_etc_hosts, os_name, kernel

echo '=== disk_etc_hosts ==='
df -h

echo '=== os_name ==='
cat /etc/os-release

echo '=== Kernel Info ==='
echo 'Kernel: 7.0.12-arch1-1'
uname -a

echo '=== Summary ==='
echo 'disk_etc_hosts=81G'
echo 'os_name=Debian GNU/Linux'
echo 'kernel=7.0.12-arch1-1'
