#!/bin/bash

# Auto-generated by Folunar Workbench
# Facts: cpu_model, os_pretty_name

echo '=== cpu_model ==='
cat /proc/cpuinfo | grep 'model name' | head -1

echo '=== OS ==='
echo 'Debian GNU/Linux 12 (bookworm)'
cat /etc/os-release 2>/dev/null | head -3

echo '=== Summary ==='
echo 'cpu_model=Intel(R) Core(TM) Ultra 9 185H'
echo 'os_pretty_name=Debian GNU/Linux 12 (bookworm)'
