#!/bin/bash

# Auto-generated by Folunar Workbench
# Facts: disk_persistent, os_version_id, os_name, kernel_release

echo '=== disk_persistent ==='
df -h

echo '=== os_version_id ==='
cat /etc/os-release

echo '=== os_name ==='
cat /etc/os-release

echo '=== kernel_release ==='
cat /proc/version

echo '=== Summary ==='
echo 'disk_persistent=109G'
echo 'os_version_id=12'
echo 'os_name=Debian GNU/Linux'
echo 'kernel_release=#1'
