#!/bin/bash

# Auto-generated by Folunar Workbench
# Facts: cpu_cores, os_version_codename

echo '=== CPU ==='
echo 'Online cores: $(nproc)'
cat /proc/loadavg

echo '=== os_version_codename ==='
cat /etc/os-release

echo '=== Summary ==='
echo 'cpu_cores=1'
echo 'os_version_codename=bookworm'
