#!/bin/bash

# Auto-generated by Folunar Workbench
# Facts: os_version_codename, kernel

echo '=== os_version_codename ==='
cat /etc/os-release

echo '=== Kernel Info ==='
echo 'Kernel: 7.0.12-arch1-1'
uname -a

echo '=== Summary ==='
echo 'os_version_codename=bookworm'
echo 'kernel=7.0.12-arch1-1'
