#!/bin/bash

# Auto-generated by Folunar Workbench
# Facts: disk_etc_hosts, os_id, cpu_model, disk_persistent

echo '=== disk_etc_hosts ==='
df -h

echo '=== os_id ==='
cat /etc/os-release

echo '=== cpu_model ==='
cat /proc/cpuinfo | grep 'model name' | head -1

echo '=== disk_persistent ==='
df -h

echo '=== Summary ==='
echo 'disk_etc_hosts=81G'
echo 'os_id=debian'
echo 'cpu_model=Intel(R) Core(TM) Ultra 9 185H'
echo 'disk_persistent=109G'
