#!/bin/bash

# Auto-generated by Folunar Workbench
# Facts: users, hostname, architecture

echo '=== users ==='
cat /etc/passwd | cut -d: -f1

echo '=== Host ==='
echo 'Hostname: 6229f8954ffb'
echo 'Hostname (cmd): $(hostname)'

echo '=== architecture ==='
cat /proc/version

echo '=== Summary ==='
echo 'users=root'
echo 'hostname=6229f8954ffb'
echo 'architecture=GNU/Linux'
