#!/bin/bash

# Auto-generated by Folunar Workbench
# Facts: kernel_release, cpu_model

echo '=== kernel_release ==='
cat /proc/version

echo '=== cpu_model ==='
cat /proc/cpuinfo | grep 'model name' | head -1

echo '=== Summary ==='
echo 'kernel_release=(linux@archlinux)'
echo 'cpu_model=Intel(R) Core(TM) Ultra 9 185H'
