#!/bin/bash

# Auto-generated by Folunar Workbench
# Facts: kernel_release, os_name, architecture, cpu_model

echo '=== kernel_release ==='
cat /proc/version

echo '=== os_name ==='
cat /etc/os-release

echo '=== architecture ==='
cat /proc/version

echo '=== cpu_model ==='
cat /proc/cpuinfo | grep 'model name' | head -1

echo '=== Summary ==='
echo 'kernel_release=#1'
echo 'os_name=Debian GNU/Linux'
echo 'architecture=+0000'
echo 'cpu_model=Intel(R) Core(TM) Ultra 9 185H'
