#!/bin/bash

# Auto-generated by Folunar Workbench
# Facts: os_name, users

echo '=== os_name ==='
cat /etc/os-release

echo '=== users ==='
cat /etc/passwd | cut -d: -f1

echo '=== Summary ==='
echo 'os_name=Debian GNU/Linux'
echo 'users=root'
