#!/bin/bash

# Auto-generated by Folunar Workbench
# Facts: cpu_model, disk_persistent, kernel_release

echo '=== cpu_model ==='
cat /proc/cpuinfo | grep 'model name' | head -1

echo '=== disk_persistent ==='
df -h

echo '=== kernel_release ==='
cat /proc/version

echo '=== Summary ==='
echo 'cpu_model=Intel(R) Core(TM) Ultra 9 185H'
echo 'disk_persistent=109G'
echo 'kernel_release=#1'
