#!/bin/bash

# Auto-generated by Folunar Workbench
# Facts: node_name, os_name

echo '=== node_name ==='
cat /proc/version

echo '=== os_name ==='
cat /etc/os-release

echo '=== Summary ==='
echo 'node_name=version'
echo 'os_name=Debian GNU/Linux'
