#!/bin/bash

# Auto-generated by Folunar Workbench
# Facts: disk_etc_hosts, os_version_id, architecture

echo '=== disk_etc_hosts ==='
df -h

echo '=== os_version_id ==='
cat /etc/os-release

echo '=== architecture ==='
cat /proc/version

echo '=== Summary ==='
echo 'disk_etc_hosts=81G'
echo 'os_version_id=12'
echo 'architecture=+0000'
