#!/bin/bash

# Auto-generated by Folunar Workbench
# Facts: disk_etc_hosts, hostname, os_version_id

echo '=== disk_etc_hosts ==='
df -h

echo '=== Host ==='
echo 'Hostname: 41c9dc728e63'
echo 'Hostname (cmd): $(hostname)'

echo '=== os_version_id ==='
cat /etc/os-release

echo '=== Summary ==='
echo 'disk_etc_hosts=81G'
echo 'hostname=41c9dc728e63'
echo 'os_version_id=12'
