#!/bin/bash

# Auto-generated by Folunar Workbench
# Facts: os_pretty_name, os_id, users

echo '=== OS ==='
echo 'Debian GNU/Linux 12 (bookworm)'
cat /etc/os-release 2>/dev/null | head -3

echo '=== os_id ==='
cat /etc/os-release

echo '=== users ==='
cat /etc/passwd | cut -d: -f1

echo '=== Summary ==='
echo 'os_pretty_name=Debian GNU/Linux 12 (bookworm)'
echo 'os_id=debian'
echo 'users=_apt,backup,bin,daemon,games,irc,list,lp'
