#!/bin/bash

# Auto-generated by Folunar Workbench
# Facts: node_name, kernel_release

echo '=== node_name ==='
cat /proc/version

echo '=== kernel_release ==='
cat /proc/version

echo '=== Summary ==='
echo 'node_name=622022a1ca5a'
echo 'kernel_release=#1'
