#!/bin/bash

# Auto-generated by Folunar Workbench
# Facts: kernel, kernel_release, disk_persistent

echo '=== Kernel Info ==='
echo 'Kernel: 7.0.12-arch1-1'
uname -a

echo '=== kernel_release ==='
cat /proc/version

echo '=== disk_persistent ==='
df -h

echo '=== Summary ==='
echo 'kernel=7.0.12-arch1-1'
echo 'kernel_release=#1'
echo 'disk_persistent=109G'
