#!/bin/bash

# Auto-generated by Folunar Workbench
# Facts: os_version_codename, os_version_id, architecture, kernel_release

echo '=== os_version_codename ==='
cat /etc/os-release

echo '=== os_version_id ==='
cat /etc/os-release

echo '=== architecture ==='
cat /proc/version

echo '=== kernel_release ==='
cat /proc/version

echo '=== Summary ==='
echo 'os_version_codename=bookworm'
echo 'os_version_id=12'
echo 'architecture=+0000'
echo 'kernel_release=#1'
