#!/bin/bash

# Auto-generated by Folunar Workbench
# Facts: os_id, kernel_release

echo '=== os_id ==='
cat /etc/os-release

echo '=== kernel_release ==='
cat /proc/version

echo '=== Summary ==='
echo 'os_id=debian'
echo 'kernel_release=#1'
