#!/bin/bash

# Auto-generated by Folunar Workbench
# Facts: node_name, disk_persistent

echo '=== node_name ==='
cat /proc/version

echo '=== disk_persistent ==='
df -h

echo '=== Summary ==='
echo 'node_name=version'
echo 'disk_persistent=109G'
