#!/bin/bash

# Auto-generated by Folunar Workbench
# Facts: kernel, hostname, os_version_codename, cpu_model

echo '=== Kernel Info ==='
echo 'Kernel: 7.0.12-arch1-1'
uname -a

echo '=== Host ==='
echo 'Hostname: 3086113ccd0f'
echo 'Hostname (cmd): $(hostname)'

echo '=== os_version_codename ==='
cat /etc/os-release

echo '=== cpu_model ==='
cat /proc/cpuinfo | grep 'model name' | head -1

echo '=== Summary ==='
echo 'kernel=7.0.12-arch1-1'
echo 'hostname=3086113ccd0f'
echo 'os_version_codename=bookworm'
echo 'cpu_model=Intel(R) Core(TM) Ultra 9 185H'
