#!/bin/bash

# Auto-generated by Folunar Workbench
# Facts: os_pretty_name, kernel

echo '=== OS ==='
echo 'Debian GNU/Linux 12 (bookworm)'
cat /etc/os-release 2>/dev/null | head -3

echo '=== Kernel Info ==='
echo 'Kernel: 7.0.12-arch1-1'
uname -a

echo '=== Summary ==='
echo 'os_pretty_name=Debian GNU/Linux 12 (bookworm)'
echo 'kernel=7.0.12-arch1-1'
