#!/bin/bash

# Auto-generated by Folunar Workbench
# Facts: os_version_codename, os_version_id, disk_etc_hosts, os_name

echo '=== os_version_codename ==='
cat /etc/os-release

echo '=== os_version_id ==='
cat /etc/os-release

echo '=== disk_etc_hosts ==='
df -h

echo '=== os_name ==='
cat /etc/os-release

echo '=== Summary ==='
echo 'os_version_codename=bookworm'
echo 'os_version_id=12'
echo 'disk_etc_hosts=81G'
echo 'os_name=Debian GNU/Linux'
