#!/bin/bash

# Auto-generated by Folunar Workbench
# Facts: architecture, os_id, disk_persistent, node_name

echo '=== architecture ==='
cat /proc/version

echo '=== os_id ==='
cat /etc/os-release

echo '=== disk_persistent ==='
df -h

echo '=== node_name ==='
cat /proc/version

echo '=== Summary ==='
echo 'architecture=+0000'
echo 'os_id=debian'
echo 'disk_persistent=109G'
echo 'node_name=version'
