#!/bin/bash

# Auto-generated by Folunar Workbench
# Facts: kernel_release, os_id

echo '=== kernel_release ==='
cat /proc/version

echo '=== os_id ==='
cat /etc/os-release

echo '=== Summary ==='
echo 'kernel_release=#1'
echo 'os_id=debian'
