#!/bin/bash

# Auto-generated by Folunar Workbench
# Facts: cpu_cores, os_version_id, os_name

echo '=== CPU ==='
echo 'Online cores: $(nproc)'
cat /proc/loadavg

echo '=== os_version_id ==='
cat /etc/os-release

echo '=== os_name ==='
cat /etc/os-release

echo '=== Summary ==='
echo 'cpu_cores=1'
echo 'os_version_id=12'
echo 'os_name=Debian GNU/Linux'
